FROM debian:stretch-slim
MAINTAINER telworks <oleg.itsm@gmail.com>
ENV build_date 2019-11-21

RUN apt-get update
#RUN yum install kernel-headers gcc gcc-c++ cpp ncurses ncurses-devel libxml2 libxml2-devel sqlite sqlite-devel openssl-devel newt-devel kernel-devel libuuid-devel net-snmp-devel xinetd tar make git -y 

ENV AUTOBUILD_UNIXTIME 1574326643

# Download asterisk.
WORKDIR /tmp/
RUN mkdir asterisk
RUN apt install -y git apt-utils
RUN git clone http://gerrit.asterisk.org/asterisk asterisk-17
RUN ls /tmp/asterisk-17
WORKDIR /tmp/asterisk-17

# Configure

RUN ls

RUN apt-get install -y wget libedit-dev  build-essential aptitude-common libboost-filesystem1.62.0 libboost-iostreams1.62.0\
  libboost-system1.62.0 libcgi-fast-perl libcgi-pm-perl libclass-accessor-perl\
  libcwidget3v5 libencode-locale-perl libfcgi-perl libgdbm3\
  libhtml-parser-perl libhtml-tagset-perl libhttp-date-perl\
  libhttp-message-perl libio-html-perl libio-string-perl\
  liblocale-gettext-perl liblwp-mediatypes-perl libparse-debianchangelog-perl\
  libperl5.24 libsigc++-2.0-0v5 libsqlite3-0 libsub-name-perl libtimedate-perl\
  liburi-perl libxapian30 netbase perl perl-modules-5.24 rename\
   apt-xapian-index debtags tasksel\
  libcwidget-dev libdata-dump-perl libhtml-template-perl libxml-simple-perl\
  libwww-perl xapian-tools perl-doc libterm-readline-gnu-perl\
  libterm-readline-perl-perl make\
  aptitude aptitude-common libboost-filesystem1.62.0 libboost-iostreams1.62.0\
  libboost-system1.62.0 libcgi-fast-perl libcgi-pm-perl libclass-accessor-perl\
  libcwidget3v5 libencode-locale-perl libfcgi-perl libgdbm3\
  libhtml-parser-perl libhtml-tagset-perl libhttp-date-perl\
  libhttp-message-perl libio-html-perl libio-string-perl\
  liblocale-gettext-perl liblwp-mediatypes-perl libparse-debianchangelog-perl\
  libperl5.24 libsigc++-2.0-0v5 libsqlite3-0 libsub-name-perl libtimedate-perl\
  liburi-perl libxapian30 netbase perl perl-modules-5.24 rename\
  sqlite3 uuid-dev  libjansson-dev  libjansson4 libxml2 libxml2-dev\
  libsqlite3-dev

RUN ls
RUN ./configure --with-jansson-bundled  --libdir=/usr/lib64 #1> /dev/null
# Remove the native build option
RUN make menuselect.makeopts
RUN menuselect/menuselect \
  --disable BUILD_NATIVE \
  --disable chan_sip \
  --enable cdr_csv \
  --enable chan_pjsip \
  --enable res_snmp \
  --enable res_http_websocket \
  menuselect.makeopts

# Continue with a standard make.
RUN make # 1> /dev/null
RUN make install # 1> /dev/null
#RUN make samples # 1> /dev/null
RUN make basic-pbx
RUN make config   

WORKDIR /

# Update max number of open files.
RUN sed -i -e 's/# MAXFILES=/MAXFILES=/' /usr/sbin/safe_asterisk
# Set tty
RUN sed -i 's/TTY=9/TTY=/g' /usr/sbin/safe_asterisk
# Create and configure asterisk for running asterisk user.
RUN useradd -m asterisk -s /sbin/nologin
RUN chown asterisk:asterisk /var/run/asterisk
RUN chown -R asterisk:asterisk /etc/asterisk/
RUN chown -R asterisk:asterisk /var/lib/asterisk
RUN chown -R asterisk:asterisk /var/log/asterisk
RUN chown -R asterisk:asterisk /var/spool/asterisk
RUN chown -R asterisk:asterisk /usr/lib64/asterisk/

# Running asterisk with user asterisk.
CMD /usr/sbin/asterisk -f -U asterisk -G asterisk -vvvg -c
